/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: m.Avramov (https://sketchfab.com/dimituravramov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sphere-9bbb81f762984ff884aee901c55c4afd
Title: Sphere
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ThreeDModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/sphere.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {if (animations.length>0) {
    actions[animations[0].name]?.play();
  }}, [actions, animations]);
  return (
    <group ref={group} {...props} dispose={null} 
    rotation={[-Math.PI / 2, -0.2, 2.2]} 
    scale={props.scale || 0.3} 
    position={props.position || [1.3, -1, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model">
          <group name="f752eb307d494818bd78947fd0a49672fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="GeoSphere001"
                  position={[-3.206, -0.019, 0.48]}
                  rotation={[Math.PI / 2, 0, 1.797]}
                  scale={1.029}>
                  <mesh
                    name="GeoSphere001_LED_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.GeoSphere001_LED_1_0.geometry}
                    material={materials.LED_1}
                  />
                </group>
                <group
                  name="GeoSphere002"
                  position={[-3.206, -0.019, 0.48]}
                  rotation={[-Math.PI / 2, 0, -2.793]}
                  scale={1.01}>
                  <mesh
                    name="GeoSphere002_LED_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.GeoSphere002_LED_1_0.geometry}
                    material={materials.LED_1}
                  />
                </group>
                <group
                  name="Text001"
                  position={[-3.206, -0.019, 0.48]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={1.076}>
                  <mesh
                    name="Text001__0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Text001__0.geometry}
                    material={materials.RootNode}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sphere.glb')
